helix/app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField
from wtforms.validators import DataRequired

class ResetAPIKeyForm(FlaskForm):
    submit = SubmitField('Submit')

helix/app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

helix/app/home/views.py
from flask import abort, render_template, flash, redirect, url_for
from flask_login import current_user, login_required
from forms import ResetAPIKeyForm
from ..models import User
from . import home
from .. import db
import uuid, sys

@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    if not current_user.is_admin:
        abort(403)
    return render_template('home/admin_dashboard.html', title="Dashboard")

@home.route('/')
def homepage():
    return render_template('home/index.html', title="Welcome")

@home.route('/dashboard')
@login_required
def dashboard():
    user = User.query.filter_by(username=current_user.username).first()
    return render_template('home/dashboard.html', user=user,title="Dashboard")

@home.route('/apikey/reset/<int:id>',methods=['GET','POST'])
@login_required
def reset_apikey(id):
    user = User.query.get_or_404(id)
    form = ResetAPIKeyForm(obj=user)
    if form.validate_on_submit():
        user.api_key = uuid.uuid4().hex
        db.session.add(user)
        db.session.commit()
        flash('You have successfully reseted the API Key.')
        return redirect(url_for('home.dashboard'))
    return render_template('home/resetapi.html',user=user, form=form, title='Reset API Key')

helix/app/templates/home/admin_dashboard.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Users{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Dashboard</h1>
        {% if user %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="30%"> Devices </th>
                  <th width="30%"> API Key </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                      <td>
                        {% if user.devices %}
                          {% for device in user.devices %}
                            <p>{{ device.name }}</p>
                          {% endfor %}
                        {% else %}
                          -
                        {% endif %}
                      </td>
                      <td> {{ user.api_key }} <br>
                        <a href="{{ url_for('home.reset_apikey',id=user.id) }}">
                            <i class="fa fa-user-plus"></i> Reset
                        </a>     
                      </td>
                    </tr>
              </tbody>
            </table>
          </div>
        {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

helix/app/templates/home/dashboard.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Users{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;"><i class="fa fa-tachometer-alt"></i> Dashboard</h1>
        {% if user %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="30%"> Devices </th>
                  <th width="30%"> API Key </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                      <td>
                        {% if user.devices %}
                          {% for device in user.devices %}
                            <p>{{ device.name }}</p>
                          {% endfor %}
                        {% else %}
                          -
                        {% endif %}
                      </td>
                      <td> {{ user.api_key }}
                        <a href="{{ url_for('home.reset_apikey',id=user.id) }}">
                            <i class="fa fa-redo"></i>
                        </a>                      
                      </td>
                    </tr>
              </tbody>
            </table>
          </div>
        {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
~                

helix/app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <img width="600" height="200" src="{{ url_for('static', filename='img/helix-banner.jpg') }}"></img> 
                    <h2 style="color:#24292e">Middleware for <span style="color:#aec251">secure</span> IoT provisioning, access and control.</h2>
                    <hr class="intro-divider">
                    <br>
                    <img width="380" height="40" src="{{ url_for('static', filename='img/powered_by_fiware.png') }}"></img>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

helix/app/templates/home/resetapi.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Reset API Key{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            <h1> Reset API Key </h1>
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}